version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/dearplain/penet
    versions:
    - 0.1.1
  - dependency-name: github.com/takama/daemon
    versions:
    - 0.12.0
