name: Release Go Binaries

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: shadowsocks-local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.11
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.3.linux-amd64.tar.gz"
        project_path: "./cmd/shadowsocks-local"
        binary_name: shadowsocks-local

  releases-matrix:
    name: shadowsocks-server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.11
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.3.linux-amd64.tar.gz"
        project_path: "./cmd/shadowsocks-server"
        binary_name: shadowsocks-server

